# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=20, unique=True)),
                ('action_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('block_type', models.CharField(choices=[('iptables', 'Iptables'), ('tcp-wrapper', 'TCP-Wrapper')], default='iptables', max_length=40)),
                ('ip_chain', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_block_type', models.CharField(blank=True, choices=[('drop', 'Drop'), ('reject', 'Reject with ICMP Message')], default='drop', max_length=40, null=True)),
                ('tcp_file', models.CharField(blank=True, max_length=80, null=True)),
                ('tcp_block_type', models.CharField(blank=True, choices=[('ALL', 'ALL'), ('SSH', 'SSH')], default='ALL', max_length=20, null=True)),
                ('action_data', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=20, unique=True)),
                ('filter_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('failregex', models.CharField(max_length=3000)),
                ('ignoreregex', models.CharField(blank=True, max_length=3000, null=True)),
                ('filter_data', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
