# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-24 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0002_auto_20160617_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='data',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
