# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-24 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0003_filter_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='data',
            new_name='filter_data',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='description',
            new_name='filter_desc',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='name',
            new_name='filter_name',
        ),
    ]
