# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-25 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0004_auto_20160624_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='description',
            new_name='action_desc',
        ),
        migrations.RemoveField(
            model_name='action',
            name='name',
        ),
        migrations.AddField(
            model_name='action',
            name='action_data',
            field=models.CharField(default=None, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='action_name',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filter',
            name='filter_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
