# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-13 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0006_auto_20160711_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jail',
            name='jail_actionvars',
        ),
    ]
