# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0005_auto_20160625_1205'),
        ('f2bmanager', '0002_customaction_customfilter'),
        ('f2bmanager', '0007_remove_jail_jail_actionvars'),
    ]

    operations = [
    ]
