# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-15 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0008_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultjail',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='defaultjail',
            name='usedns',
        ),
        migrations.RemoveField(
            model_name='jail',
            name='backend',
        ),
        migrations.RemoveField(
            model_name='jail',
            name='usedns',
        ),
    ]
