# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-15 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0009_auto_20160715_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaction',
            name='ip_block_type',
            field=models.CharField(blank=True, choices=[('DROP', 'Drop'), ('REJECT --reject-with icmp-port-unreachable', 'Reject with ICMP Message')], default='drop', max_length=40, null=True),
        ),
    ]
