# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-15 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0011_auto_20160715_0826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
