# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-15 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0012_auto_20160715_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultjail',
            name='ignoreip',
            field=models.CharField(blank=True, default='127.0.0.1/8', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jail',
            name='ignoreip',
            field=models.CharField(blank=True, default='127.0.0.1/8', max_length=500, null=True),
        ),
    ]
