# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0013_auto_20160715_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaction',
            name='tcp_block_type',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('sshd', 'SSH')], default='ALL', max_length=20, null=True),
        ),
    ]
