# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-11 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='days',
            field=models.IntegerField(default=5),
        ),
    ]
