# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-11 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0003_host_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('host', 'jail')]),
        ),
    ]
