# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-14 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f2bmanager', '0007_remove_jail_jail_actionvars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
